services:
  plex:
    image: 844633438632.dkr.ecr.eu-west-2.amazonaws.com/voting-app:plex
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      resources:
        limits:
          cpus: '4'
          memory: 8192M
    depends_on:
      - plex-orchestrator
      - plex-worker
    environment:
      DOCKER_MODS: "ghcr.io/pabloromeo/clusterplex_dockermod:latest"
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      ORCHESTRATOR_URL: http://plex-orchestrator:3500
      PMS_SERVICE: plex     # This service. If you disable Local Relay then you must use PMS_IP instead
      PMS_PORT: "32400"
      TRANSCODE_OPERATING_MODE: local #(local|remote|both)
      TRANSCODER_VERBOSE: "1"   # 1=verbose, 0=silent
      LOCAL_RELAY_ENABLED: "1"
      LOCAL_RELAY_PORT: "32499"
    healthcheck:
      test: curl -fsS http://localhost:32400/identity > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 300s
    volumes:
      - plex-data:/config
      - plex-data:/data/tv
      - plex-data:/data/movies
      - plex-data:/transcode
    ports:
#      - 32499:32499     # LOCAL_RELAY_PORT
      - 32400:32400
#      - 3005:3005
#      - 8324:8324
#      - 1900:1900/udp
#      - 32410:32410/udp
#      - 32412:32412/udp
#      - 32413:32413/udp
#      - 32414:32414/udp
    networks:
      - frontend

  plex-orchestrator:
    image: 844633438632.dkr.ecr.eu-west-2.amazonaws.com/voting-app:clusterplex_orchestrator
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      resources:
        limits:
          cpus: '4'
          memory: 8192M
    healthcheck:
      test: curl -fsS http://localhost:3500/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    environment:
      TZ: Europe/London
      LISTENING_PORT: 3500
      WORKER_SELECTION_STRATEGY: "LOAD_RANK" # RR | LOAD_CPU | LOAD_TASKS | LOAD_RANK (default)
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3500:3500
    networks:
      - frontend

  plex-worker:
    image: 844633438632.dkr.ecr.eu-west-2.amazonaws.com/voting-app:plex
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      resources:
        limits:
          cpus: '4'
          memory: 8192M
    depends_on:
      - plex-orchestrator
    environment:
      DOCKER_MODS: "ghcr.io/pabloromeo/clusterplex_worker_dockermod:latest"
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      LISTENING_PORT: 3501      # used by the healthcheck
      STAT_CPU_INTERVAL: 2000   # interval for reporting worker load metrics
      ORCHESTRATOR_URL: http://plex-orchestrator:3500
      EAE_SUPPORT: "1"
    healthcheck:
      test: curl -fsS http://localhost:3501/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 240s
    volumes:
      - plex-data:/codecs # (optional)
      - plex-data:/data/tv
      - plex-data:/data/movies
      - plex-data:/transcode
    networks:
      - frontend
      
networks:
  frontend:
  
volumes:
  plex-data: